### ISSUE TITLE
Problems when running with webpack-dev-server

### ISSUE THREAD

**Issue by k-sheth** [xz64/license-webpack-plugin#9] opened 2017-01-16 10:19 UTC
Hi

Thanks for this plugin. I get an error when running with webpack-dev-server

Here are my dependencies,

webpack: 2.2.0-rc.6
webpack-dev-server: 2.2.0-rc.0
license-webpack-plugin: latest

plugin options - 
                new LicensesPlugin({
                    //filename: 'licenses.txt',
                    pattern: /^(.*)$/,
                    includeUndefined: true,
                    addLicenseText: true,
                    addUrl: true,
                }),

I get the following stacktrace - 

fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: ENOENT: no such file or directory, open '/Users/ksheth/myproj/web/3rdpartylicenses.txt'
    at Object.fs.openSync (fs.js:558:51)
    at Object.fs.writeFileSync (fs.js:1223:33)
    at licensePlugin.write (/Users/ksheth/myproj/node_modules/license-webpack-plugin/index.js:178:8)
    at licensePlugin.<anonymous> (/Users/ksheth/myproj/node_modules/license-webpack-plugin/index.js:198:12)
    at Compiler.applyPlugins (/Users/ksheth/myproj/node_modules/webpack/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/ksheth/myproj/node_modules/webpack/lib/Compiler.js:91:17)
    at /Users/ksheth/myproj/node_modules/webpack/lib/Compiler.js:74:18
    at Compiler.emitRecords (/Users/ksheth/myproj/node_modules/webpack/lib/Compiler.js:348:37)
    at /Users/ksheth/myproj/node_modules/webpack/lib/Compiler.js:57:19
    at /Users/ksheth/myproj/node_modules/webpack/lib/Compiler.js:341:11
    at next (/Users/ksheth/myproj/node_modules/webpack/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/ksheth/myproj/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/ksheth/myproj/node_modules/webpack/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/ksheth/myproj/node_modules/webpack/lib/Compiler.js:338:8)
    at Compiler.<anonymous> (/Users/ksheth/myproj/node_modules/webpack/lib/Compiler.js:333:14)
    at /Users/ksheth/myproj/node_modules/webpack/node_modules/async/dist/async.js:356:16

Thanks,

**Comment by xz64** [comment] 2017-01-19 04:28
Hi, are you using clean-webpack-plugin by any chance? I was able to reproduce this issue on one of my projects using webpack 2.2.0. The license-webpack-plugin will try to write to your build output directory, after it has been deleted by clean-webpack-plugin, causing this error.

Since webpack-dev-server serves files from memory, the output directory doesn't get created on the file system.

Fixed in v0.4.2 by creating output directory on the file system if it doesn't exist

**Closed** 2017-01-19 04:28 UTC

**Comment by k-sheth** [comment] 2017-01-23 09:33
Apologies for the delayed reply. No, I do not use the clean-webpack-plugin.

**Comment by xz64** [comment] 2017-01-23 17:19
Let me know if you are still getting the error using license-webpack-plugin v0.4.2 and provide a minimal setup replicating the issue if so.

**Comment by k-sheth** [comment] 2017-01-24 02:51
Works now. Thanks for the quick update!
